
CREATE DATABASE ERIK_TRX;
USE ERIK_TRX;
CREATE TABLE `ACCOUNT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(20) NOT NULL,
  `BALANCE` decimal(16,6) DEFAULT '0.000000',
PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO ERIK_TRX.ACCOUNT VALUES (1,'tom',10000),(2,'merry',10000);